name: No Broken Links

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  no-broken-links:
    name: Broken Link Checker
    runs-on: warp-ubuntu-latest-x64-2x
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0

      - name: Run Mintlify Script
        run: npx mintlify broken-links
