name: Vale

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions: read-all

jobs:
  vale:
    name: Vale Lanugage Review
    runs-on: warp-ubuntu-latest-x64-2x
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@reviewdog
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          vale_flags: --glob=*.mdx
          fail_on_error: true
